# Apply Skip to an Evmos node
- hosts: evmos-*
  gather_facts: false
  become: false

  vars:
    ####################################################################################
    # Variables to customize for your installation
    ####################################################################################

    # Daemon name. This will be restarted at the end of the playbook. 
    # Use `evmosd` if not using Cosmosvisor, or `cosmosvisor` if you are.
    - daemon: evmosd 
    # daemon: cosmosvisor

    # Personal peer IDs if needed.
    - personal_peer_ids: ''

    ####################################################################################
    # Other variables - You likely don't need to modify anything below this line.
    ####################################################################################

    #-----------------------------------------
    # Configuration for git checkout
    #-----------------------------------------

    # Repositority to clone
    - repo: https://github.com/evmos/evmos

    # Version to checkout (tag, commit, or branch)
    - node_version: v9.1.0

    # Where to clone the code to. This folder is automatically cleaned up.
    - git_checkout_dir: evmos-source

    #-----------------------------------------
    # Configuration for Skip
    #-----------------------------------------
    
    # Version of Skip's MEV Tendermint to substitute into the node.
    - skip_version: v0.34.22-mev.9
    # Skip sentinel peer
    - sentinel_peer_string: "c0a2990e2a5dad7f4ace044d2f936de6891c6f0a@evmos_9001-2-sentinel.skip.money:26656"
    # Skip sentinel RPC
    - sentinel_rpc_string: "http://evmos_9001-2-api.skip.money"

    #-----------------------------------------
    # Configuration for Node
    #-----------------------------------------
    
    # Data folder for the node
    - folder: '.evmosd'

  roles:
    - apply-skip
