# Apply Skip to a Juno node
- hosts: juno-*
  gather_facts: false
  become: false

  vars:
    ####################################################################################
    # Variables to customize for your installation
    ####################################################################################

    # Daemon name. This will be restarted at the end of the playbook. 
    # Use `junod` if not using Cosmosvisor, or `cosmosvisor` if you are.
    - daemon: junod 
    # daemon: cosmosvisor

    # Personal peer IDs if needed.
    - personal_peer_ids: ''

    ####################################################################################
    # Other variables - You likely don't need to modify anything below this line.
    ####################################################################################

    #-----------------------------------------
    # Configuration for git checkout
    #-----------------------------------------

    # Repositority to clone
    - repo: https://github.com/CosmosContracts/juno

    # Version to checkout (tag, commit, or branch)
    - node_version: v13.0.0

    # Where to clone the code to. This folder is automatically cleaned up.
    - git_checkout_dir: juno-source

    #-----------------------------------------
    # Configuration for Skip
    #-----------------------------------------
    
    # Version of Skip's MEV Tendermint to substitute into the node.
    - skip_version: v0.34.26-mev.15
    # Skip sentinel peer
    - sentinel_peer_string: "8dd5dfefe8959f7186e6c80bdb87dbd919534677@juno-1-sentinel.skip.money:26656"
    # Skip sentinel RPC
    - sentinel_rpc_string: "http://juno-1-api.skip.money"

    #-----------------------------------------
    # Configuration for Node
    #-----------------------------------------
    
    # Data folder for the node
    - folder: '.juno'

  roles:
    - apply-skip
